#!/usr/bin/env python3
# 加密的camera_cmd模块
import sys
import os
import base64
import types

_script_dir = os.path.dirname(os.path.abspath(__file__))
if _script_dir not in sys.path:
  sys.path.insert(0, _script_dir)

ENCODED_SOURCE = '''
IyEvdXNyL2Jpbi9lbnYgcHl0aG9uMwoiIiIKQ2FtZXJhIENvbW1hbmQgVG9vbCAtIFB1cmUgUHl0aG9uIGltcGxlbWVudGF0aW9uClJlcGxhY2VzIGNhbWVyYV9jbWQuc2ggZm9yIHNlbmRpbmcgY2FtZXJhIGNhbGlicmF0aW9uIGNvbW1hbmRzCiIiIgoKaW1wb3J0IHN5cwppbXBvcnQgdGltZQppbXBvcnQgb3MKZnJvbSAuZGF0YWJ1cyBpbXBvcnQgRGF0YUJ1cywgZmluZF9zZXJpYWxfcG9ydApmcm9tIC5wYWNrIGltcG9ydCBDbWRQYWNrCgoKZGVmIGNhbWVyYV9jYWxpYl9jYWxsYmFjayhjYW1lcmFfcGFjayk6CiAgICAiIiLmkYTlg4/lpLTmoIflrprmlbDmja7lm57osIPlh73mlbAiIiIKICAgIHByaW50KCLmkYTlg4/lpLTmoIflrprmlbDmja7lt7LmjqXmlLYiKQoKCmRlZiBtYWluKCk6CiAgICAiIiLkuLvlh73mlbAiIiIKICAgIHVzYWdlID0gIiIiCueUqOazlToKICDljZXorr7lpIfmqKHlvI86IHB5dGhvbiAtbSBnZW5fY29udHJvbGxlcl9weXRob25fc2RrLmNhbWVyYV9jbWQgezEyMzR8Y2FtZXJhcmN8Y2FtZXJhcmx8Y2FtZXJhcnJ8TUNVSUR9CiAgCiAg5Y+v6YCJ546v5aKD5Y+Y6YePOiBTRVJJQUxfUE9SVD0vZGV2L3R0eVVTQjAg5oyH5a6a5Liy5Y+j6K6+5aSHCiAgCiAg5Y+C5pWw6K+05piOOgogICAgMTIzNCAgICAgIC0g5qCH5a6a5a6M5oiQ56Gu6K6kCiAgICBjYW1lcmFyYyAgLSDkuK3pl7Tnm7jmnLrmoIflrprvvIjnlJ/miJBjYW0wX3NlbnNvci55YW1s77yJCiAgICBjYW1lcmFybCAgLSDlt6bkvqfnm7jmnLrmoIflrprvvIjnlJ/miJBjYW0xX3NlbnNvci55YW1s77yJCiAgICBjYW1lcmFyciAgLSDlj7Pkvqfnm7jmnLrmoIflrprvvIjnlJ/miJBjYW0yX3NlbnNvci55YW1s77yJCiAgICBNQ1VJRCAgICAgLSDmn6Xor6Lorr7lpIdNQ1VJRAogICAgIiIiCiAgICAKICAgIGlmIGxlbihzeXMuYXJndikgPCAyOgogICAgICAgIHByaW50KHVzYWdlKQogICAgICAgIHN5cy5leGl0KDEpCiAgICAKICAgIHJlY29yZF92YWx1ZSA9IHN5cy5hcmd2WzFdCiAgICAKICAgICMg5qCh6aqMUkVDT1JEX1ZBTFVFCiAgICB2YWxpZF9jb21tYW5kcyA9IFsnMTIzNCcsICdjYW1lcmFyYycsICdjYW1lcmFybCcsICdjYW1lcmFycicsICdNQ1VJRCddCiAgICBpZiByZWNvcmRfdmFsdWUgbm90IGluIHZhbGlkX2NvbW1hbmRzOgogICAgICAgIHByaW50KGYi6ZSZ6K+vOiDlj4LmlbDlv4XpobvmmK8ge3ZhbGlkX2NvbW1hbmRzfSDkuYvkuIAiKQogICAgICAgIHByaW50KHVzYWdlKQogICAgICAgIHN5cy5leGl0KDEpCiAgICAKICAgICMg5qC55o2u5Lyg5YWl55qE5ZG95Luk5Y+C5pWw5Yaz5a6a55Sf5oiQ55qEWUFNTOaWh+S7tuWQjQogICAgeWFtbF9maWxlbmFtZSA9ICIiCiAgICBpZiByZWNvcmRfdmFsdWUgPT0gImNhbWVyYXJjIjoKICAgICAgICB5YW1sX2ZpbGVuYW1lID0gImNhbTBfc2Vuc29yLnlhbWwiCiAgICBlbGlmIHJlY29yZF92YWx1ZSA9PSAiY2FtZXJhcmwiOgogICAgICAgIHlhbWxfZmlsZW5hbWUgPSAiY2FtMV9zZW5zb3IueWFtbCIKICAgIGVsaWYgcmVjb3JkX3ZhbHVlID09ICJjYW1lcmFyciI6CiAgICAgICAgeWFtbF9maWxlbmFtZSA9ICJjYW0yX3NlbnNvci55YW1sIgogICAgCiAgICAjIOiuvue9rllBTUzmlofku7blkI3liLDnjq/looPlj5jph4/vvIzkvptNZXNzYWdlUGFja+S9v+eUqAogICAgaWYgeWFtbF9maWxlbmFtZToKICAgICAgICAjIOiOt+WPlmdlbl9jb250cm9sbGVyX3B5dGhvbl9zZGvnm67lvZXnmoTnu53lr7not6/lvoTvvIjlvZPliY3mlofku7bmiYDlnKjnm67lvZXvvIkKICAgICAgICBzY3JpcHRfZGlyID0gb3MucGF0aC5kaXJuYW1lKG9zLnBhdGguZGlybmFtZShvcy5wYXRoLmFic3BhdGgoX19maWxlX18pKSkKICAgICAgICAjIFlBTUzmlofku7blsIbkv53lrZjliLBnZW5fY29udHJvbGxlcl9weXRob25fc2RrL2NhbGliX3Jlc3VsdOebruW9lQogICAgICAgIHJlc3VsdF9kaXIgPSBvcy5wYXRoLmpvaW4oc2NyaXB0X2RpciwgImNhbGliX3Jlc3VsdCIpCiAgICAgICAgCiAgICAgICAgb3MuZW52aXJvblsnQ0FMSUJfWUFNTF9GSUxFTkFNRSddID0geWFtbF9maWxlbmFtZQogICAgICAgIHByaW50KGYi5bCG55Sf5oiQWUFNTOaWh+S7tjoge3lhbWxfZmlsZW5hbWV9IikKICAgICAgICBwcmludChmIuS/neWtmOi3r+W+hDoge29zLnBhdGguam9pbihyZXN1bHRfZGlyLCB5YW1sX2ZpbGVuYW1lKX0iKQogICAgZWxzZToKICAgICAgICAjIOehruS/neayoeaciei/meS4queOr+Wig+WPmOmHjwogICAgICAgIGlmICdDQUxJQl9ZQU1MX0ZJTEVOQU1FJyBpbiBvcy5lbnZpcm9uOgogICAgICAgICAgICBkZWwgb3MuZW52aXJvblsnQ0FMSUJfWUFNTF9GSUxFTkFNRSddCiAgICAKICAgICMg5Liy5Y+j6YCJ5oup77ya5LyY5YWI5L2/55So546v5aKD5Y+Y6YeP77yM5ZCm5YiZ5p+l5om+5bey6YWN572u55qE6K6+5aSHCiAgICBzZXJpYWxfcG9ydCA9IG9zLmVudmlyb24uZ2V0KCdTRVJJQUxfUE9SVCcsICcnKQogICAgaWYgbm90IHNlcmlhbF9wb3J0OgogICAgICAgIHNlcmlhbF9wb3J0ID0gZmluZF9zZXJpYWxfcG9ydCgidHR5VVNCIikgICMgZmluZF9zZXJpYWxfcG9ydOeOsOWcqOWPquafpeaJvuW3sumFjee9rueahOiuvuWkhwogICAgCiAgICBpZiBub3Qgc2VyaWFsX3BvcnQ6CiAgICAgICAgcHJpbnQoIuKdjCDmnKrmib7liLDlt7LphY3nva7nmoTkuLLlj6Porr7lpIciKQogICAgICAgIHN5cy5leGl0KDEpCiAgICAKICAgIHByaW50KGYi5L2/55So5Liy5Y+jOiB7c2VyaWFsX3BvcnR9IikKICAgIHByaW50KGYi5Y+R6YCB55u45py65qCH5a6a5oyH5LukOiB7cmVjb3JkX3ZhbHVlfSIpCiAgICAKICAgICMg5bu656uL5oC757q/5bm25Y+R6YCB5ZG95LukCiAgICB0cnk6CiAgICAgICAgYnVzID0gRGF0YUJ1cygKICAgICAgICAgICAgdHR5X3BvcnQ9c2VyaWFsX3BvcnQsCiAgICAgICAgICAgIGJhdWRyYXRlPTkyMTYwMCwKICAgICAgICAgICAgaXNfY2FsaWJfY21kPVRydWUsCiAgICAgICAgICAgIGNhbWVyYV9jYWxpYl9jYWxsYmFjaz1jYW1lcmFfY2FsaWJfY2FsbGJhY2ssCiAgICAgICAgKQogICAgICAgIHRpbWUuc2xlZXAoMS4wKSAgIyDpooTnlZnorr7lpIfliJ3lp4vljJbml7bpl7QKICAgICAgICBidXMuYWRkX2NtZChDbWRQYWNrLnBhY2tfY2FsaWIocmVjb3JkPXJlY29yZF92YWx1ZS5lbmNvZGUoInV0Zi04IikpKQogICAgICAgIHRpbWUuc2xlZXAoMC41KSAgIyDpooTnlZnorr7lpIflpITnkIbml7bpl7QKICAgICAgICAKICAgICAgICAjIOetieW+heWTjeW6lAogICAgICAgIHByaW50KCLnrYnlvoXorr7lpIflk43lupQuLi4iKQogICAgICAgIHRpbWUuc2xlZXAoMi4wKQogICAgICAgIAogICAgICAgIGJ1cy5zdG9wKCkKICAgICAgICAKICAgICAgICAjIOeJueauiuWRveS7pOeahOWkhOeQhgogICAgICAgIGlmIHJlY29yZF92YWx1ZSA9PSAiMTIzNCI6CiAgICAgICAgICAgIHByaW50KCLinIUgQ2FsaWJyYXRpb24gT0sgISIpCiAgICAgICAgZWxpZiByZWNvcmRfdmFsdWUgPT0gIk1DVUlEIjoKICAgICAgICAgICAgcHJpbnQoIuKchSBNQ1VJRCBxdWVyeSBleGVjdXRlZCIpCiAgICAgICAgZWxzZToKICAgICAgICAgICAgcHJpbnQoZiLinIUg5a6M5oiQ5Y+R6YCBIHtyZWNvcmRfdmFsdWV9IOaMh+S7pCIpCiAgICAgICAgICAgIGlmIHlhbWxfZmlsZW5hbWU6CiAgICAgICAgICAgICAgICAjIOajgOafpeaWh+S7tuaYr+WQpuW3sueUn+aIkOWcqGNhbGliX3Jlc3VsdOebruW9lQogICAgICAgICAgICAgICAgc2NyaXB0X2RpciA9IG9zLnBhdGguZGlybmFtZShvcy5wYXRoLmRpcm5hbWUob3MucGF0aC5hYnNwYXRoKF9fZmlsZV9fKSkpCiAgICAgICAgICAgICAgICByZXN1bHRfZGlyID0gb3MucGF0aC5qb2luKHNjcmlwdF9kaXIsICJjYWxpYl9yZXN1bHQiKQogICAgICAgICAgICAgICAgeWFtbF9wYXRoID0gb3MucGF0aC5qb2luKHJlc3VsdF9kaXIsIHlhbWxfZmlsZW5hbWUpCiAgICAgICAgICAgICAgICBpZiBvcy5wYXRoLmV4aXN0cyh5YW1sX3BhdGgpOgogICAgICAgICAgICAgICAgICAgIHByaW50KGYi4pyFIFlBTUzmlofku7blt7LnlJ/miJA6IHt5YW1sX3BhdGh9IikKICAgICAgICAgICAgICAgIGVsc2U6CiAgICAgICAgICAgICAgICAgICAgcHJpbnQoZiLimqDvuI8gWUFNTOaWh+S7tuacqueUn+aIkO+8jOivt+ajgOafpeiuvuWkh+WTjeW6lCIpCiAgICBleGNlcHQgRXhjZXB0aW9uIGFzIGU6CiAgICAgICAgcHJpbnQoZiLinYwg6ZSZ6K+vOiB7ZX0iKQogICAgICAgIGltcG9ydCB0cmFjZWJhY2sKICAgICAgICB0cmFjZWJhY2sucHJpbnRfZXhjKCkKICAgICAgICBzeXMuZXhpdCgxKQoKCmlmIF9fbmFtZV9fID09ICJfX21haW5fXyI6CiAgICBtYWluKCkK
'''

def _decode_and_execute():
  """解码并执行源码，返回模块的全局命名空间"""
  try:
    source_code = base64.b64decode(ENCODED_SOURCE).decode('utf-8')
    code = compile(source_code, 'camera_cmd.py', 'exec')
    
    import builtins
    globals_dict = {
      '__name__': 'gen_controller_sdk_python.camera_cmd',
      '__file__': __file__,
      '__package__': 'gen_controller_sdk_python',
      '__builtins__': builtins,
    }
    
    exec(code, globals_dict)
    return globals_dict
  except Exception as e:
    print(f"解码错误: {e}")
    import traceback
    traceback.print_exc()
    raise

# 解码并获取原始模块的全局命名空间
_original_globals = _decode_and_execute()

# 导出原始模块的所有非私有符号
for name, value in _original_globals.items():
  if not name.startswith('_') and name not in globals():
    globals()[name] = value

# 定义main函数，用于脚本执行
def main():
  """主函数 - 用于脚本执行"""
  try:
    if 'main' in _original_globals:
      sys.argv[0] = 'camera_cmd.py'
      _original_globals['main']()
    else:
      print("错误: 找不到main函数")
      sys.exit(1)
  except Exception as e:
    print(f"执行错误: {e}")
    import traceback
    traceback.print_exc()
    sys.exit(1)

if __name__ == '__main__':
  main()
